source: 
  type: file
  path: C:\Users\Jose\go\src\dev\readyamltest\testfiles\json\test.json
  extension: json
destination: 
  type: db
  table: testtable
  structure: 
  - fields: value1
  - field2: value2
  - field3: value3