source: 
  type: file
  path: C:\Users\Jose\go\src\dev\readyamltest\testfiles\xml\test.xml
  extension: xml
destination: 
  type: db
  table: testtable
  structure: 
  - fields: value1
  - field2: value2
  - field3: value3