version: '3'

services:
  centos:
    image: centos/mysql-57-centos7
    container_name: centos
    ports:
      - 3310:3306
    environment:
      # MYSQL_ROOT_PASSWORD: root_bsc
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: db
    volumes:
      - ./dump:/container-entrypoint
    # networks:
    #   - centos_network
  # program:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - .:/go/src/app
  #   networks:
  #     - centos_network
  #   depends_on: 
  #     - centos
# networks: 
#   centos_network: